### ISSUE TITLE
Mojo 2.5.0.0 Event Calendar Pro Cannot Edit Event

### ISSUE THREAD

**Issue by joedavis01** [i7MEDIA/mojoportal#67] opened 2017-08-07 15:22 UTC
I have installed the latest Mojo 2.5.0.0 build on my local dev machine and I am having a problem with the Event Calendar Pro Add-On.  
 
I can create an event however when I click on any other tab besides Event Settings to add a description and or summary the entire screen goes white and nothing ever loads. I thought this strange so I tried it on the demo site and the same thing happened.. 

I am using Google Chrome 59.03 as my browser..

**Comment by Isaac-Hall** [comment] 2017-08-07 22:16
Hi Joe,

Good catch! This bug is caused by the CSS Handler creating an invalid URL that is being rejected by IIS as dangerous. You can work around it for now by opening your main.css file inside your skin, and removing the `@import url("https://fonts.googleapis.com/css?family=Roboto:300,400,500,700")` call at the very beginning of the file, after the comments.

If you want to keep your font, you can add this to your layout.master after the comment on line 13: 
`<link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,500,500i,700,700i" rel="stylesheet">`

We'll be fixing this in the next release. Thanks!

**Comment by joedavis01** [comment] 2017-08-08 01:47
Thanks.. update worked great..

**Comment by ElijahFowler** [comment] 2017-08-17 17:57
This is fixed in by these 6a3ec02b093994c4cb5e3f7e09d3506c9a94eff / 89fb006d78815993440da34833aef647acab4c78 in the source code and will be in the next release.

**Closed by ElijahFowler** 2017-08-17 17:57 UTC

**Comment by joedavis01** [comment] 2017-08-17 18:53
Great Job !!!
