### ISSUE TITLE
Linked Images not Displayed in Forum Posts

### ISSUE THREAD

**Issue by joseph-fowler** [i7MEDIA/mojoportal#171] opened 2023-03-10 22:27 UTC
Pictures added to forum posts via URL aren't displayed 

- JPG and PNG files were both tested 
- Images uploaded to the "images" directory display correctly

**Comment by JosephMDavis** [comment] 2023-03-10 22:35
This is related to NeatHtml. I don't recall if it's by design or not. I thought we had a trusted user concept that would allow users who were marked as trusted to link to external resources.

**Comment by JosephMDavis** [comment] 2023-05-26 14:04
This is by design. There is a "Trusted" option on the user record. If that's not enabled, the users external images will not show. [See documentation here](https://www.mojoportal.com/allowing-users-to-post-images-in-the-forums). Admittedly, that documentation is written well and the info about the "trusted" option needs to be placed elsewhere because it's not only for forums.

**Closed by JosephMDavis** 2023-05-26 14:04 UTC
Labels: invalid
